/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.netcracker.scp.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LabDetails service. Represents a row in the &quot;Portlets_LabDetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.netcracker.scp.model.impl.LabDetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.netcracker.scp.model.impl.LabDetailsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LabDetails
 * @see com.netcracker.scp.model.impl.LabDetailsImpl
 * @see com.netcracker.scp.model.impl.LabDetailsModelImpl
 * @generated
 */
@ProviderType
public interface LabDetailsModel extends BaseModel<LabDetails>, GroupedModel,
	ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a lab details model instance should use the {@link LabDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this lab details.
	 *
	 * @return the primary key of this lab details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this lab details.
	 *
	 * @param primaryKey the primary key of this lab details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this lab details.
	 *
	 * @return the uuid of this lab details
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this lab details.
	 *
	 * @param uuid the uuid of this lab details
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the lab ID of this lab details.
	 *
	 * @return the lab ID of this lab details
	 */
	public long getLabId();

	/**
	 * Sets the lab ID of this lab details.
	 *
	 * @param labId the lab ID of this lab details
	 */
	public void setLabId(long labId);

	/**
	 * Returns the group ID of this lab details.
	 *
	 * @return the group ID of this lab details
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this lab details.
	 *
	 * @param groupId the group ID of this lab details
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this lab details.
	 *
	 * @return the company ID of this lab details
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this lab details.
	 *
	 * @param companyId the company ID of this lab details
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this lab details.
	 *
	 * @return the user ID of this lab details
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this lab details.
	 *
	 * @param userId the user ID of this lab details
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this lab details.
	 *
	 * @return the user uuid of this lab details
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this lab details.
	 *
	 * @param userUuid the user uuid of this lab details
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this lab details.
	 *
	 * @return the user name of this lab details
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this lab details.
	 *
	 * @param userName the user name of this lab details
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this lab details.
	 *
	 * @return the create date of this lab details
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this lab details.
	 *
	 * @param createDate the create date of this lab details
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this lab details.
	 *
	 * @return the modified date of this lab details
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this lab details.
	 *
	 * @param modifiedDate the modified date of this lab details
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the title of this lab details.
	 *
	 * @return the title of this lab details
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this lab details.
	 *
	 * @param title the title of this lab details
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this lab details.
	 *
	 * @return the description of this lab details
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this lab details.
	 *
	 * @param description the description of this lab details
	 */
	public void setDescription(String description);

	/**
	 * Returns the portal url of this lab details.
	 *
	 * @return the portal url of this lab details
	 */
	@AutoEscape
	public String getPortalUrl();

	/**
	 * Sets the portal url of this lab details.
	 *
	 * @param portalUrl the portal url of this lab details
	 */
	public void setPortalUrl(String portalUrl);

	/**
	 * Returns the nc url of this lab details.
	 *
	 * @return the nc url of this lab details
	 */
	@AutoEscape
	public String getNcUrl();

	/**
	 * Sets the nc url of this lab details.
	 *
	 * @param ncUrl the nc url of this lab details
	 */
	public void setNcUrl(String ncUrl);

	/**
	 * Returns the other url of this lab details.
	 *
	 * @return the other url of this lab details
	 */
	@AutoEscape
	public String getOtherUrl();

	/**
	 * Sets the other url of this lab details.
	 *
	 * @param otherUrl the other url of this lab details
	 */
	public void setOtherUrl(String otherUrl);

	/**
	 * Returns the vim user of this lab details.
	 *
	 * @return the vim user of this lab details
	 */
	@AutoEscape
	public String getVimUser();

	/**
	 * Sets the vim user of this lab details.
	 *
	 * @param vimUser the vim user of this lab details
	 */
	public void setVimUser(String vimUser);

	/**
	 * Returns the vim pass of this lab details.
	 *
	 * @return the vim pass of this lab details
	 */
	@AutoEscape
	public String getVimPass();

	/**
	 * Sets the vim pass of this lab details.
	 *
	 * @param vimPass the vim pass of this lab details
	 */
	public void setVimPass(String vimPass);

	/**
	 * Returns the sdn user of this lab details.
	 *
	 * @return the sdn user of this lab details
	 */
	@AutoEscape
	public String getSdnUser();

	/**
	 * Sets the sdn user of this lab details.
	 *
	 * @param sdnUser the sdn user of this lab details
	 */
	public void setSdnUser(String sdnUser);

	/**
	 * Returns the sdn pass of this lab details.
	 *
	 * @return the sdn pass of this lab details
	 */
	@AutoEscape
	public String getSdnPass();

	/**
	 * Sets the sdn pass of this lab details.
	 *
	 * @param sdnPass the sdn pass of this lab details
	 */
	public void setSdnPass(String sdnPass);

	/**
	 * Returns the bass link of this lab details.
	 *
	 * @return the bass link of this lab details
	 */
	@AutoEscape
	public String getBassLink();

	/**
	 * Sets the bass link of this lab details.
	 *
	 * @param bassLink the bass link of this lab details
	 */
	public void setBassLink(String bassLink);

	/**
	 * Returns the status of this lab details.
	 *
	 * @return the status of this lab details
	 */
	public boolean getStatus();

	/**
	 * Returns <code>true</code> if this lab details is status.
	 *
	 * @return <code>true</code> if this lab details is status; <code>false</code> otherwise
	 */
	public boolean isStatus();

	/**
	 * Sets whether this lab details is status.
	 *
	 * @param status the status of this lab details
	 */
	public void setStatus(boolean status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LabDetails labDetails);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LabDetails> toCacheModel();

	@Override
	public LabDetails toEscapedModel();

	@Override
	public LabDetails toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}