create table Portlets_Events (
	uuid_ VARCHAR(75) null,
	eventId LONG not null primary key,
	labId LONG,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	title VARCHAR(75) null,
	description VARCHAR(75) null,
	startTime DATE null,
	endTime DATE null,
	activityType VARCHAR(75) null,
	fullDay BOOLEAN,
	portalUser VARCHAR(75) null,
	portalPass VARCHAR(75) null,
	ncUser VARCHAR(75) null,
	ncPass VARCHAR(75) null,
	status INTEGER
);

create table Portlets_LabDetails (
	uuid_ VARCHAR(75) null,
	labId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	title VARCHAR(75) null,
	description VARCHAR(75) null,
	portalUrl VARCHAR(75) null,
	ncUrl VARCHAR(75) null,
	otherUrl VARCHAR(75) null,
	vimUser VARCHAR(75) null,
	vimPass VARCHAR(75) null,
	sdnUser VARCHAR(75) null,
	sdnPass VARCHAR(75) null,
	bassLink VARCHAR(75) null,
	status BOOLEAN
);